spring.application.name=flutter_server


spring.mvc.hiddenmethod.filter.enabled=true
spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://58.239.58.243:3306/java502_team1_db?characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.hikari.username=java502_team2
spring.datasource.hikari.password=java502_team2_1234
spring.datasource.hikari.connection-test-query=SELECT 1

mybatis.configuration.map-underscore-to-camel-case=true

mybatis.mapper-locations=classpath:sql/**/*.xml
mybatis.type-aliases-package=bitc.next502.team_prj.dto

spring.devtools.livereload.enabled=true
spring.thymeleaf.cache=false

server.servlet.session.timeout=30m

